/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DbTestRouteImport } from './routes/db-test'
import { Route as ServicesTestRouteImport } from './routes/services-test'
import { Route as CapsterAccountRouteImport } from './routes/capster.account'
import { Route as CapsterCheckInRouteImport } from './routes/capster.check-in'
import { Route as CapsterDashboardRouteImport } from './routes/capster.dashboard'
import { Route as CapsterEndShiftRouteImport } from './routes/capster.end-shift'
import { Route as CapsterLoginRouteImport } from './routes/capster.login'
import { Route as CapsterServicesRouteImport } from './routes/capster.services'
import { Route as CapsterShiftSavedRouteImport } from './routes/capster.shift-saved'
import { Route as CapsterTransactionsRouteImport } from './routes/capster.transactions'
import { Route as CustomerCapsterRouteImport } from './routes/customer.capster'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as CustomerCompletedRouteImport } from './routes/customer.completed'
import { Route as CustomerCustomerInfoRouteImport } from './routes/customer.customer-info'
import { Route as CustomerPaymentRouteImport } from './routes/customer.payment'
import { Route as CustomerPaymentConfirmationRouteImport } from './routes/customer.payment-confirmation'
import { Route as CustomerServiceExecutionRouteImport } from './routes/customer.service-execution'
import { Route as CustomerServicesRouteImport } from './routes/customer.services'
import { Route as CustomerSuccessRouteImport } from './routes/customer.success'
import { Route as CapsterTransactionsTransactionIdRouteImport } from './routes/capster.transactions.$transactionId'
import { Route as CapsterTransactionsManualRouteImport } from './routes/capster.transactions.manual'
import { Route as CapsterTransactionsSuccessRouteImport } from './routes/capster.transactions.success'
import { Route as CapsterTransactionsTodayRouteImport } from './routes/capster.transactions.today'
import { Route as CustomerReceiptTransactionIdRouteImport } from './routes/customer.receipt.$transactionId'
import { Route as CapsterTransactionsTransactionIdReceiptRouteImport } from './routes/capster.transactions.$transactionId.receipt'
import { Route as CapsterTransactionsManualCapsterRouteImport } from './routes/capster.transactions.manual.capster'
import { Route as CapsterTransactionsManualDetailRouteImport } from './routes/capster.transactions.manual.detail'
import { Route as CapsterTransactionsManualPaymentRouteImport } from './routes/capster.transactions.manual.payment'
import { Route as CapsterTransactionsManualServicesRouteImport } from './routes/capster.transactions.manual.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbTestRoute = DbTestRouteImport.update({
  id: '/db-test',
  path: '/db-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTestRoute = ServicesTestRouteImport.update({
  id: '/services-test',
  path: '/services-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterAccountRoute = CapsterAccountRouteImport.update({
  id: '/capster/account',
  path: '/capster/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterCheckInRoute = CapsterCheckInRouteImport.update({
  id: '/capster/check-in',
  path: '/capster/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterDashboardRoute = CapsterDashboardRouteImport.update({
  id: '/capster/dashboard',
  path: '/capster/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterEndShiftRoute = CapsterEndShiftRouteImport.update({
  id: '/capster/end-shift',
  path: '/capster/end-shift',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterLoginRoute = CapsterLoginRouteImport.update({
  id: '/capster/login',
  path: '/capster/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterServicesRoute = CapsterServicesRouteImport.update({
  id: '/capster/services',
  path: '/capster/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterShiftSavedRoute = CapsterShiftSavedRouteImport.update({
  id: '/capster/shift-saved',
  path: '/capster/shift-saved',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterTransactionsRoute = CapsterTransactionsRouteImport.update({
  id: '/capster/transactions',
  path: '/capster/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCapsterRoute = CustomerCapsterRouteImport.update({
  id: '/customer/capster',
  path: '/customer/capster',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/customer/cart',
  path: '/customer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCompletedRoute = CustomerCompletedRouteImport.update({
  id: '/customer/completed',
  path: '/customer/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCustomerInfoRoute = CustomerCustomerInfoRouteImport.update({
  id: '/customer/customer-info',
  path: '/customer/customer-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPaymentRoute = CustomerPaymentRouteImport.update({
  id: '/customer/payment',
  path: '/customer/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPaymentConfirmationRoute =
  CustomerPaymentConfirmationRouteImport.update({
    id: '/customer/payment-confirmation',
    path: '/customer/payment-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerServiceExecutionRoute =
  CustomerServiceExecutionRouteImport.update({
    id: '/customer/service-execution',
    path: '/customer/service-execution',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerServicesRoute = CustomerServicesRouteImport.update({
  id: '/customer/services',
  path: '/customer/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSuccessRoute = CustomerSuccessRouteImport.update({
  id: '/customer/success',
  path: '/customer/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsterTransactionsTransactionIdRoute =
  CapsterTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => CapsterTransactionsRoute,
  } as any)
const CapsterTransactionsManualRoute =
  CapsterTransactionsManualRouteImport.update({
    id: '/manual',
    path: '/manual',
    getParentRoute: () => CapsterTransactionsRoute,
  } as any)
const CapsterTransactionsSuccessRoute =
  CapsterTransactionsSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => CapsterTransactionsRoute,
  } as any)
const CapsterTransactionsTodayRoute =
  CapsterTransactionsTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => CapsterTransactionsRoute,
  } as any)
const CustomerReceiptTransactionIdRoute =
  CustomerReceiptTransactionIdRouteImport.update({
    id: '/customer/receipt/$transactionId',
    path: '/customer/receipt/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CapsterTransactionsTransactionIdReceiptRoute =
  CapsterTransactionsTransactionIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => CapsterTransactionsTransactionIdRoute,
  } as any)
const CapsterTransactionsManualCapsterRoute =
  CapsterTransactionsManualCapsterRouteImport.update({
    id: '/capster',
    path: '/capster',
    getParentRoute: () => CapsterTransactionsManualRoute,
  } as any)
const CapsterTransactionsManualDetailRoute =
  CapsterTransactionsManualDetailRouteImport.update({
    id: '/detail',
    path: '/detail',
    getParentRoute: () => CapsterTransactionsManualRoute,
  } as any)
const CapsterTransactionsManualPaymentRoute =
  CapsterTransactionsManualPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => CapsterTransactionsManualRoute,
  } as any)
const CapsterTransactionsManualServicesRoute =
  CapsterTransactionsManualServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => CapsterTransactionsManualRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db-test': typeof DbTestRoute
  '/services-test': typeof ServicesTestRoute
  '/capster/account': typeof CapsterAccountRoute
  '/capster/check-in': typeof CapsterCheckInRoute
  '/capster/dashboard': typeof CapsterDashboardRoute
  '/capster/end-shift': typeof CapsterEndShiftRoute
  '/capster/login': typeof CapsterLoginRoute
  '/capster/services': typeof CapsterServicesRoute
  '/capster/shift-saved': typeof CapsterShiftSavedRoute
  '/capster/transactions': typeof CapsterTransactionsRouteWithChildren
  '/customer/capster': typeof CustomerCapsterRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/completed': typeof CustomerCompletedRoute
  '/customer/customer-info': typeof CustomerCustomerInfoRoute
  '/customer/payment': typeof CustomerPaymentRoute
  '/customer/payment-confirmation': typeof CustomerPaymentConfirmationRoute
  '/customer/service-execution': typeof CustomerServiceExecutionRoute
  '/customer/services': typeof CustomerServicesRoute
  '/customer/success': typeof CustomerSuccessRoute
  '/capster/transactions/$transactionId': typeof CapsterTransactionsTransactionIdRouteWithChildren
  '/capster/transactions/manual': typeof CapsterTransactionsManualRouteWithChildren
  '/capster/transactions/success': typeof CapsterTransactionsSuccessRoute
  '/capster/transactions/today': typeof CapsterTransactionsTodayRoute
  '/customer/receipt/$transactionId': typeof CustomerReceiptTransactionIdRoute
  '/capster/transactions/$transactionId/receipt': typeof CapsterTransactionsTransactionIdReceiptRoute
  '/capster/transactions/manual/capster': typeof CapsterTransactionsManualCapsterRoute
  '/capster/transactions/manual/detail': typeof CapsterTransactionsManualDetailRoute
  '/capster/transactions/manual/payment': typeof CapsterTransactionsManualPaymentRoute
  '/capster/transactions/manual/services': typeof CapsterTransactionsManualServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db-test': typeof DbTestRoute
  '/services-test': typeof ServicesTestRoute
  '/capster/account': typeof CapsterAccountRoute
  '/capster/check-in': typeof CapsterCheckInRoute
  '/capster/dashboard': typeof CapsterDashboardRoute
  '/capster/end-shift': typeof CapsterEndShiftRoute
  '/capster/login': typeof CapsterLoginRoute
  '/capster/services': typeof CapsterServicesRoute
  '/capster/shift-saved': typeof CapsterShiftSavedRoute
  '/capster/transactions': typeof CapsterTransactionsRouteWithChildren
  '/customer/capster': typeof CustomerCapsterRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/completed': typeof CustomerCompletedRoute
  '/customer/customer-info': typeof CustomerCustomerInfoRoute
  '/customer/payment': typeof CustomerPaymentRoute
  '/customer/payment-confirmation': typeof CustomerPaymentConfirmationRoute
  '/customer/service-execution': typeof CustomerServiceExecutionRoute
  '/customer/services': typeof CustomerServicesRoute
  '/customer/success': typeof CustomerSuccessRoute
  '/capster/transactions/$transactionId': typeof CapsterTransactionsTransactionIdRouteWithChildren
  '/capster/transactions/manual': typeof CapsterTransactionsManualRouteWithChildren
  '/capster/transactions/success': typeof CapsterTransactionsSuccessRoute
  '/capster/transactions/today': typeof CapsterTransactionsTodayRoute
  '/customer/receipt/$transactionId': typeof CustomerReceiptTransactionIdRoute
  '/capster/transactions/$transactionId/receipt': typeof CapsterTransactionsTransactionIdReceiptRoute
  '/capster/transactions/manual/capster': typeof CapsterTransactionsManualCapsterRoute
  '/capster/transactions/manual/detail': typeof CapsterTransactionsManualDetailRoute
  '/capster/transactions/manual/payment': typeof CapsterTransactionsManualPaymentRoute
  '/capster/transactions/manual/services': typeof CapsterTransactionsManualServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/db-test': typeof DbTestRoute
  '/services-test': typeof ServicesTestRoute
  '/capster/account': typeof CapsterAccountRoute
  '/capster/check-in': typeof CapsterCheckInRoute
  '/capster/dashboard': typeof CapsterDashboardRoute
  '/capster/end-shift': typeof CapsterEndShiftRoute
  '/capster/login': typeof CapsterLoginRoute
  '/capster/services': typeof CapsterServicesRoute
  '/capster/shift-saved': typeof CapsterShiftSavedRoute
  '/capster/transactions': typeof CapsterTransactionsRouteWithChildren
  '/customer/capster': typeof CustomerCapsterRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/completed': typeof CustomerCompletedRoute
  '/customer/customer-info': typeof CustomerCustomerInfoRoute
  '/customer/payment': typeof CustomerPaymentRoute
  '/customer/payment-confirmation': typeof CustomerPaymentConfirmationRoute
  '/customer/service-execution': typeof CustomerServiceExecutionRoute
  '/customer/services': typeof CustomerServicesRoute
  '/customer/success': typeof CustomerSuccessRoute
  '/capster/transactions/$transactionId': typeof CapsterTransactionsTransactionIdRouteWithChildren
  '/capster/transactions/manual': typeof CapsterTransactionsManualRouteWithChildren
  '/capster/transactions/success': typeof CapsterTransactionsSuccessRoute
  '/capster/transactions/today': typeof CapsterTransactionsTodayRoute
  '/customer/receipt/$transactionId': typeof CustomerReceiptTransactionIdRoute
  '/capster/transactions/$transactionId/receipt': typeof CapsterTransactionsTransactionIdReceiptRoute
  '/capster/transactions/manual/capster': typeof CapsterTransactionsManualCapsterRoute
  '/capster/transactions/manual/detail': typeof CapsterTransactionsManualDetailRoute
  '/capster/transactions/manual/payment': typeof CapsterTransactionsManualPaymentRoute
  '/capster/transactions/manual/services': typeof CapsterTransactionsManualServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/db-test'
    | '/services-test'
    | '/capster/account'
    | '/capster/check-in'
    | '/capster/dashboard'
    | '/capster/end-shift'
    | '/capster/login'
    | '/capster/services'
    | '/capster/shift-saved'
    | '/capster/transactions'
    | '/customer/capster'
    | '/customer/cart'
    | '/customer/completed'
    | '/customer/customer-info'
    | '/customer/payment'
    | '/customer/payment-confirmation'
    | '/customer/service-execution'
    | '/customer/services'
    | '/customer/success'
    | '/capster/transactions/$transactionId'
    | '/capster/transactions/manual'
    | '/capster/transactions/success'
    | '/capster/transactions/today'
    | '/customer/receipt/$transactionId'
    | '/capster/transactions/$transactionId/receipt'
    | '/capster/transactions/manual/capster'
    | '/capster/transactions/manual/detail'
    | '/capster/transactions/manual/payment'
    | '/capster/transactions/manual/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/db-test'
    | '/services-test'
    | '/capster/account'
    | '/capster/check-in'
    | '/capster/dashboard'
    | '/capster/end-shift'
    | '/capster/login'
    | '/capster/services'
    | '/capster/shift-saved'
    | '/capster/transactions'
    | '/customer/capster'
    | '/customer/cart'
    | '/customer/completed'
    | '/customer/customer-info'
    | '/customer/payment'
    | '/customer/payment-confirmation'
    | '/customer/service-execution'
    | '/customer/services'
    | '/customer/success'
    | '/capster/transactions/$transactionId'
    | '/capster/transactions/manual'
    | '/capster/transactions/success'
    | '/capster/transactions/today'
    | '/customer/receipt/$transactionId'
    | '/capster/transactions/$transactionId/receipt'
    | '/capster/transactions/manual/capster'
    | '/capster/transactions/manual/detail'
    | '/capster/transactions/manual/payment'
    | '/capster/transactions/manual/services'
  id:
    | '__root__'
    | '/'
    | '/db-test'
    | '/services-test'
    | '/capster/account'
    | '/capster/check-in'
    | '/capster/dashboard'
    | '/capster/end-shift'
    | '/capster/login'
    | '/capster/services'
    | '/capster/shift-saved'
    | '/capster/transactions'
    | '/customer/capster'
    | '/customer/cart'
    | '/customer/completed'
    | '/customer/customer-info'
    | '/customer/payment'
    | '/customer/payment-confirmation'
    | '/customer/service-execution'
    | '/customer/services'
    | '/customer/success'
    | '/capster/transactions/$transactionId'
    | '/capster/transactions/manual'
    | '/capster/transactions/success'
    | '/capster/transactions/today'
    | '/customer/receipt/$transactionId'
    | '/capster/transactions/$transactionId/receipt'
    | '/capster/transactions/manual/capster'
    | '/capster/transactions/manual/detail'
    | '/capster/transactions/manual/payment'
    | '/capster/transactions/manual/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbTestRoute: typeof DbTestRoute
  ServicesTestRoute: typeof ServicesTestRoute
  CapsterAccountRoute: typeof CapsterAccountRoute
  CapsterCheckInRoute: typeof CapsterCheckInRoute
  CapsterDashboardRoute: typeof CapsterDashboardRoute
  CapsterEndShiftRoute: typeof CapsterEndShiftRoute
  CapsterLoginRoute: typeof CapsterLoginRoute
  CapsterServicesRoute: typeof CapsterServicesRoute
  CapsterShiftSavedRoute: typeof CapsterShiftSavedRoute
  CapsterTransactionsRoute: typeof CapsterTransactionsRouteWithChildren
  CustomerCapsterRoute: typeof CustomerCapsterRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCompletedRoute: typeof CustomerCompletedRoute
  CustomerCustomerInfoRoute: typeof CustomerCustomerInfoRoute
  CustomerPaymentRoute: typeof CustomerPaymentRoute
  CustomerPaymentConfirmationRoute: typeof CustomerPaymentConfirmationRoute
  CustomerServiceExecutionRoute: typeof CustomerServiceExecutionRoute
  CustomerServicesRoute: typeof CustomerServicesRoute
  CustomerSuccessRoute: typeof CustomerSuccessRoute
  CustomerReceiptTransactionIdRoute: typeof CustomerReceiptTransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-test': {
      id: '/db-test'
      path: '/db-test'
      fullPath: '/db-test'
      preLoaderRoute: typeof DbTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-test': {
      id: '/services-test'
      path: '/services-test'
      fullPath: '/services-test'
      preLoaderRoute: typeof ServicesTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/account': {
      id: '/capster/account'
      path: '/capster/account'
      fullPath: '/capster/account'
      preLoaderRoute: typeof CapsterAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/check-in': {
      id: '/capster/check-in'
      path: '/capster/check-in'
      fullPath: '/capster/check-in'
      preLoaderRoute: typeof CapsterCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/dashboard': {
      id: '/capster/dashboard'
      path: '/capster/dashboard'
      fullPath: '/capster/dashboard'
      preLoaderRoute: typeof CapsterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/end-shift': {
      id: '/capster/end-shift'
      path: '/capster/end-shift'
      fullPath: '/capster/end-shift'
      preLoaderRoute: typeof CapsterEndShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/login': {
      id: '/capster/login'
      path: '/capster/login'
      fullPath: '/capster/login'
      preLoaderRoute: typeof CapsterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/services': {
      id: '/capster/services'
      path: '/capster/services'
      fullPath: '/capster/services'
      preLoaderRoute: typeof CapsterServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/shift-saved': {
      id: '/capster/shift-saved'
      path: '/capster/shift-saved'
      fullPath: '/capster/shift-saved'
      preLoaderRoute: typeof CapsterShiftSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/transactions': {
      id: '/capster/transactions'
      path: '/capster/transactions'
      fullPath: '/capster/transactions'
      preLoaderRoute: typeof CapsterTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/capster': {
      id: '/customer/capster'
      path: '/customer/capster'
      fullPath: '/customer/capster'
      preLoaderRoute: typeof CustomerCapsterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/customer/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/completed': {
      id: '/customer/completed'
      path: '/customer/completed'
      fullPath: '/customer/completed'
      preLoaderRoute: typeof CustomerCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/customer-info': {
      id: '/customer/customer-info'
      path: '/customer/customer-info'
      fullPath: '/customer/customer-info'
      preLoaderRoute: typeof CustomerCustomerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/payment': {
      id: '/customer/payment'
      path: '/customer/payment'
      fullPath: '/customer/payment'
      preLoaderRoute: typeof CustomerPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/payment-confirmation': {
      id: '/customer/payment-confirmation'
      path: '/customer/payment-confirmation'
      fullPath: '/customer/payment-confirmation'
      preLoaderRoute: typeof CustomerPaymentConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/service-execution': {
      id: '/customer/service-execution'
      path: '/customer/service-execution'
      fullPath: '/customer/service-execution'
      preLoaderRoute: typeof CustomerServiceExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/services': {
      id: '/customer/services'
      path: '/customer/services'
      fullPath: '/customer/services'
      preLoaderRoute: typeof CustomerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/success': {
      id: '/customer/success'
      path: '/customer/success'
      fullPath: '/customer/success'
      preLoaderRoute: typeof CustomerSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/transactions/$transactionId': {
      id: '/capster/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/capster/transactions/$transactionId'
      preLoaderRoute: typeof CapsterTransactionsTransactionIdRouteImport
      parentRoute: typeof CapsterTransactionsRoute
    }
    '/capster/transactions/manual': {
      id: '/capster/transactions/manual'
      path: '/manual'
      fullPath: '/capster/transactions/manual'
      preLoaderRoute: typeof CapsterTransactionsManualRouteImport
      parentRoute: typeof CapsterTransactionsRoute
    }
    '/capster/transactions/success': {
      id: '/capster/transactions/success'
      path: '/success'
      fullPath: '/capster/transactions/success'
      preLoaderRoute: typeof CapsterTransactionsSuccessRouteImport
      parentRoute: typeof CapsterTransactionsRoute
    }
    '/capster/transactions/today': {
      id: '/capster/transactions/today'
      path: '/today'
      fullPath: '/capster/transactions/today'
      preLoaderRoute: typeof CapsterTransactionsTodayRouteImport
      parentRoute: typeof CapsterTransactionsRoute
    }
    '/customer/receipt/$transactionId': {
      id: '/customer/receipt/$transactionId'
      path: '/customer/receipt/$transactionId'
      fullPath: '/customer/receipt/$transactionId'
      preLoaderRoute: typeof CustomerReceiptTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capster/transactions/$transactionId/receipt': {
      id: '/capster/transactions/$transactionId/receipt'
      path: '/receipt'
      fullPath: '/capster/transactions/$transactionId/receipt'
      preLoaderRoute: typeof CapsterTransactionsTransactionIdReceiptRouteImport
      parentRoute: typeof CapsterTransactionsTransactionIdRoute
    }
    '/capster/transactions/manual/capster': {
      id: '/capster/transactions/manual/capster'
      path: '/capster'
      fullPath: '/capster/transactions/manual/capster'
      preLoaderRoute: typeof CapsterTransactionsManualCapsterRouteImport
      parentRoute: typeof CapsterTransactionsManualRoute
    }
    '/capster/transactions/manual/detail': {
      id: '/capster/transactions/manual/detail'
      path: '/detail'
      fullPath: '/capster/transactions/manual/detail'
      preLoaderRoute: typeof CapsterTransactionsManualDetailRouteImport
      parentRoute: typeof CapsterTransactionsManualRoute
    }
    '/capster/transactions/manual/payment': {
      id: '/capster/transactions/manual/payment'
      path: '/payment'
      fullPath: '/capster/transactions/manual/payment'
      preLoaderRoute: typeof CapsterTransactionsManualPaymentRouteImport
      parentRoute: typeof CapsterTransactionsManualRoute
    }
    '/capster/transactions/manual/services': {
      id: '/capster/transactions/manual/services'
      path: '/services'
      fullPath: '/capster/transactions/manual/services'
      preLoaderRoute: typeof CapsterTransactionsManualServicesRouteImport
      parentRoute: typeof CapsterTransactionsManualRoute
    }
  }
}

interface CapsterTransactionsTransactionIdRouteChildren {
  CapsterTransactionsTransactionIdReceiptRoute: typeof CapsterTransactionsTransactionIdReceiptRoute
}

const CapsterTransactionsTransactionIdRouteChildren: CapsterTransactionsTransactionIdRouteChildren =
  {
    CapsterTransactionsTransactionIdReceiptRoute:
      CapsterTransactionsTransactionIdReceiptRoute,
  }

const CapsterTransactionsTransactionIdRouteWithChildren =
  CapsterTransactionsTransactionIdRoute._addFileChildren(
    CapsterTransactionsTransactionIdRouteChildren,
  )

interface CapsterTransactionsManualRouteChildren {
  CapsterTransactionsManualCapsterRoute: typeof CapsterTransactionsManualCapsterRoute
  CapsterTransactionsManualDetailRoute: typeof CapsterTransactionsManualDetailRoute
  CapsterTransactionsManualPaymentRoute: typeof CapsterTransactionsManualPaymentRoute
  CapsterTransactionsManualServicesRoute: typeof CapsterTransactionsManualServicesRoute
}

const CapsterTransactionsManualRouteChildren: CapsterTransactionsManualRouteChildren =
  {
    CapsterTransactionsManualCapsterRoute:
      CapsterTransactionsManualCapsterRoute,
    CapsterTransactionsManualDetailRoute: CapsterTransactionsManualDetailRoute,
    CapsterTransactionsManualPaymentRoute:
      CapsterTransactionsManualPaymentRoute,
    CapsterTransactionsManualServicesRoute:
      CapsterTransactionsManualServicesRoute,
  }

const CapsterTransactionsManualRouteWithChildren =
  CapsterTransactionsManualRoute._addFileChildren(
    CapsterTransactionsManualRouteChildren,
  )

interface CapsterTransactionsRouteChildren {
  CapsterTransactionsTransactionIdRoute: typeof CapsterTransactionsTransactionIdRouteWithChildren
  CapsterTransactionsManualRoute: typeof CapsterTransactionsManualRouteWithChildren
  CapsterTransactionsSuccessRoute: typeof CapsterTransactionsSuccessRoute
  CapsterTransactionsTodayRoute: typeof CapsterTransactionsTodayRoute
}

const CapsterTransactionsRouteChildren: CapsterTransactionsRouteChildren = {
  CapsterTransactionsTransactionIdRoute:
    CapsterTransactionsTransactionIdRouteWithChildren,
  CapsterTransactionsManualRoute: CapsterTransactionsManualRouteWithChildren,
  CapsterTransactionsSuccessRoute: CapsterTransactionsSuccessRoute,
  CapsterTransactionsTodayRoute: CapsterTransactionsTodayRoute,
}

const CapsterTransactionsRouteWithChildren =
  CapsterTransactionsRoute._addFileChildren(CapsterTransactionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbTestRoute: DbTestRoute,
  ServicesTestRoute: ServicesTestRoute,
  CapsterAccountRoute: CapsterAccountRoute,
  CapsterCheckInRoute: CapsterCheckInRoute,
  CapsterDashboardRoute: CapsterDashboardRoute,
  CapsterEndShiftRoute: CapsterEndShiftRoute,
  CapsterLoginRoute: CapsterLoginRoute,
  CapsterServicesRoute: CapsterServicesRoute,
  CapsterShiftSavedRoute: CapsterShiftSavedRoute,
  CapsterTransactionsRoute: CapsterTransactionsRouteWithChildren,
  CustomerCapsterRoute: CustomerCapsterRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerCompletedRoute: CustomerCompletedRoute,
  CustomerCustomerInfoRoute: CustomerCustomerInfoRoute,
  CustomerPaymentRoute: CustomerPaymentRoute,
  CustomerPaymentConfirmationRoute: CustomerPaymentConfirmationRoute,
  CustomerServiceExecutionRoute: CustomerServiceExecutionRoute,
  CustomerServicesRoute: CustomerServicesRoute,
  CustomerSuccessRoute: CustomerSuccessRoute,
  CustomerReceiptTransactionIdRoute: CustomerReceiptTransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
